// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  concepts: [
    {
      type: 'autogenerated',
      dirName: 'concepts',
    },
  ],
  playbooks: [
    {
      type: 'autogenerated',
      dirName: 'playbooks',
    },
  ],
  systemDesign: [
    {
      type: 'autogenerated',
      dirName: 'system-design',
    },
  ],
};

module.exports = sidebars;
