/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate sidebars from filesystem structure
  mentalModels: [
    {
      type: 'autogenerated',
      dirName: 'mental-models',
    },
  ],
  playbooks: [
    {
      type: 'autogenerated',
      dirName: 'playbooks',
    },
  ],
  systemDesign: [
    {
      type: 'autogenerated',
      dirName: 'system-design',
    },
  ],
  experiments: [
    {
      type: 'autogenerated',
      dirName: 'experiments',
    },
  ],
};

module.exports = sidebars;
